"""empty message

Revision ID: 00bdd507090e
Revises: 9227682e98f9
Create Date: 2025-06-17 00:39:18.370061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bdd507090e'
down_revision = '9227682e98f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('folder_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'otteruser', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('folder_user_id_fkey'), 'otteruser', ['user_id'], ['id'])

    # ### end Alembic commands ###
