"""empty message

Revision ID: 410b2e2d8b2e
Revises: 3366ad234620
Create Date: 2025-07-12 16:20:16.985565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410b2e2d8b2e'
down_revision = '3366ad234620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('playlistid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
