"""added cascades to everything

Revision ID: 9227682e98f9
Revises: 
Create Date: 2025-06-16 23:52:41.729142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9227682e98f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversations_folder_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'folder', ['folder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('folder_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'otteruser', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_convo_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['convo'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_convo_fkey'), 'conversations', ['convo'], ['id'])

    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('folder_user_id_fkey'), 'otteruser', ['user_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversations_folder_id_fkey'), 'folder', ['folder_id'], ['id'])

    # ### end Alembic commands ###
